### ISSUE TITLE
Teams personal app - White screen after password change

### ISSUE THREAD

**Issue by PieterHeemeryck** [SharePoint/sp-dev-training-spfx-teams-dev#11]
Hi

We've had some issues with clients having a white screen when opening our custom personal app for Teams (SPFx) - only on the desktop Teams app, not the web browser. It happens whenever an end user has changed his / her password. I'm fairly certain it has to do with the desktop app caching auth tokens that are no longer valid after the password change.

For now, as a 3rd party app developer, there isn't much we can do besides asking the user to log out, log in and cross our fingers.

Is this on the radar of the SPFx & Teams product teams ? Are there other solutions to this problem ?

PS: we are following the approach outlined by Vesa in this [video](https://www.youtube.com/watch?v=IGBKOreRu3M).

**Comment by andrewconnell** [comment]
This isn't the right place for issues... issues about the content itself go here, but for SP development issues, you should post them to https://aka.ms/spdev-issues

**Comment by PieterHeemeryck** [comment]
My bad, thanks for redirecting me!
