### ISSUE TITLE
Configuration and content pages

### ISSUE THREAD

**Issue by akatsiubka** [SharePoint/sp-dev-training-spfx-teams-dev#7]
Is it possible to use custom configuration page and SharePoint built-in teamshostedapp.aspx page as a content page at the same time? 
If it is not possible, how can I change teams logo when I add a new tab?
![Add a tab](https://user-images.githubusercontent.com/15927481/71615371-a2e3be80-2bb9-11ea-9af6-0522780ca941.png)

**Comment by andrewconnell** [comment]
There's no option to change this. It's an aspect to the SPFx+Teams integration and a difference between the two things. The workaround the SharePoint team provided was to open the property pane after the tab was created.
