### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by ncmadhan1989** [SharePoint/sp-dev-training-spfx-teams-dev#9]
in this example for getting teams context " this.context.microsoftTeams" is used,
but i read the document like from spfx 1.10 this context is changed to  this.context.sdks.microsoftTeams 
still the this.context.microsoftTeams is exists in spfx 1.10? and if its what is the difference between the both,kindly clarify,its confused a lot :'(

**Comment by andrewconnell** [comment]
Look at the last bullet point in this section in the v1.10 release
https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.10-release-notes#what-is-deprecated--getting-removed

We'll be updating the module to reflect this change when we refresh the module this quarter.
